### ISSUE TITLE
NETFramework

### ISSUE THREAD

**Issue by sec13b** [Workingdaturah/Payload-Generator#3]
Hi, only v4.8 can be used, more computers use old NETFramework , like 4.5 or 4.6

**Comment by sec13b** [comment]
p.s.: detected: 17/26

**Comment by dmcxblue** [comment]
If you have the NetFramework installed from your VS installation you can just replace that 4.8 to your liking, also it's not meant to be Evasive it's an Aggressor script meant for the operator to build upon it and automate your payload building

**Comment by sec13b** [comment]
ok .
Thank you
